### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by gohansaneric** [Nico-Posada/Geometry-Dash-2.2-Stat-Editor#8]
why when i go to download my windows defender says its a virus plus when i check with other virus checkers it says it has like 11 trojans installed and info stealers and stuff? this is kinda sus ngl and that it requires admin to run is even more sus
![image_2024-02-25_122508270](https://github.com/Nico-Posada/Geometry-Dash-2.2-Stat-Editor/assets/157242955/32179927-bb3e-44f4-9951-b8ec743b1e5d)

**Comment by Nico-Posada** [comment]
It's great that you're being cautious with these types of things, great practice, but it requires admin because it's using ReadProcessMemory and WriteProcessMemory which may be where those VirusTotal/Windows Defender detections are coming from.

I'm not going to tell you what to do, but this is an open source project for a reason (so people can see the source code). There aren't that many files to look through if you're feeling suspicious, and if you want to be safe, just compile the project on your own instead of running the compiled binary I have provided. This project is set up in a way where building the executable can be done just by running the .bat file given (after installing Visual Studio). If you still don't trust it, I'm not really sure what to tell you, but it's not the end of the world if you can't edit your stats.
